---
- name: Create unprivledged folders
  become: no
  file:
      path: "{{item}}"
      state: directory
      mode: 0755
      recurse: yes
  with_items:
  - "{{ansible_user_dir}}/{{php_software_directory}}"

- name: Install Required Packages
  become: yes
  package:
      name: "{{item}}"
      state: present
  with_items:
  - "curl"

- name: Download PhpStorm Tarball
  become: no
  get_url:
      url: "https://download.jetbrains.com/webide/PhpStorm-{{php_phpstorm_version}}.tar.gz"
      dest: "{{ansible_user_dir}}/{{php_download_directory}}/phpstorm-{{php_phpstorm_version}}.tar.gz"
      mode: 0444
  when: php_phpstorm_install

- name: Uncompress PhpStorm Tarball
  become: no
  unarchive:
      src: "{{ansible_user_dir}}/{{php_download_directory}}/phpstorm-{{php_phpstorm_version}}.tar.gz"
      dest: "{{ansible_user_dir}}/{{php_software_directory}}"
      copy: no
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      mode: 0555
      creates: "{{ansible_user_dir}}/{{php_software_directory}}/PhpStorm-{{php_phpstorm_build}}/build.txt"
  when: php_phpstorm_install

- name: Create Softlink To PhpStorm
  become: no
  file:
      src: "{{ansible_user_dir}}/{{php_software_directory}}/PhpStorm-{{php_phpstorm_build}}"
      dest: "{{ansible_user_dir}}/{{php_software_directory}}/phpstorm"
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      state: link
  when: php_phpstorm_install

- name: Create Desktop Icon For PhpStorm
  become: no
  template:
      src: "templates/phpstorm.desktop.j2"
      dest: "{{ansible_user_dir}}/Desktop/phpstorm.desktop"
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      mode: 0555
  when: php_phpstorm_install

