---
- name: Download PhpStorm Tarball
  become: no
  get_url:
      url: "https://download.jetbrains.com/webide/PhpStorm-{{php_phpstorm_version}}.tar.gz"
      dest: "{{ansible_user_dir}}/{{base_download_directory}}/phpstorm-{{php_phpstorm_version}}.tar.gz"
      mode: 0444
  when: php_phpstorm_install

- name: Uncompress PhpStorm Tarball
  become: no
  unarchive:
      src: "{{ansible_user_dir}}/{{base_download_directory}}/phpstorm-{{php_phpstorm_version}}.tar.gz"
      dest: "{{ansible_user_dir}}/{{base_software_directory}}"
      copy: no
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      mode: 0555
      creates: "{{ansible_user_dir}}/{{base_software_directory}}/PhpStorm-{{php_phpstorm_build}}/build.txt"
  when: php_phpstorm_install

- name: Create Softlink To PhpStorm
  become: no
  file:
      src: "{{ansible_user_dir}}/{{base_software_directory}}/PhpStorm-{{php_phpstorm_build}}"
      dest: "{{ansible_user_dir}}/{{base_software_directory}}/phpstorm"
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      state: link
  when: php_phpstorm_install

- name: Create Desktop Icon For PhpStorm
  become: no
  template:
      src: "templates/phpstorm.desktop.j2"
      dest: "{{ansible_user_dir}}/Desktop/phpstorm.desktop"
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      mode: 0755
  when: php_phpstorm_install

- name: Set Global Environment To Have PhpStorm Use Shared JDK
  become: yes
  template:
      src: "templates/phpstorm-environment.sh.j2"
      dest: "/etc/profile.d/phpstorm-environment.sh"
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      mode: 0555
  when: php_phpstorm_share_jdk

- name: Remove PhpStorms's Embedded JDK
  become: no
  file:
      path: "{{ansible_user_dir}}/{{base_software_directory}}/phpstorm/jre"
      state: absent
  when: php_phpstorm_share_jdk

